# Jekyll AMP!
# This config file is meant for settings that affect the entire site/blog.
# When this file is changed, you have to restart the server process

# Site settings
title: Jekyll AMP
email: emailaddress@email.com
description: >
  Google's AMP using Jekyll
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Brian'
bio: >
  Brian OToole
author_image: "/assets/images/author.jpg"
twitter_username: brianotoole
github_username:  brianotoole

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
